name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.gitattributes'

permissions:
  contents: read

jobs:
  composer-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - run: composer validate --strict --ansi

  composer-normalize:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer normalize --dry-run --diff --ansi

  php-cs-fixer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer csfixer -- --format=checkstyle --ansi | cs2pr

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer phpstan -- --ansi

  rector:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer rector -- --ansi

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: imagick
          tools: composer:v2
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --optimize-autoloader --ansi
      - run: composer test
